spring:
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT # serverTimezone=GMT这是设置时区
    username: root
    password: 123456


logging:
  level:
    com.wxh.dao: debug
#mybatis:
#  模型所在包名
#  type-aliases-package: com.wxh.model
#  映射文件路径
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:SqlMapConfig.xml
server:
  port:
